workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_OPEN_MERGE_REQUESTS && $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED == 'true'
      when: never
    - when: always
                #when: always: This rule is a catch-all. 
                #It means that if none of the previous rules apply, the pipeline will always run.

default:
  tags:
    - local

stages:
  - setup
  - deploy

pre_kubeconfig:
  stage: .pre
  script:
    - echo "Setting up KUBECONFIG"
    - export KUBECONFIG=$DEV_KUBE_CONFIG  # Export KUBECONFIG variable for all stages
    - cat $DEV_KUBE_CONFIG > $CI_PROJECT_DIR/kubeconfig
  tags:
    - laptop
  artifacts:
    paths:
      - $CI_PROJECT_DIR/kubeconfig 
    expire_in: 1h  # Set artifact expiration
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH


setup_helm:
  stage: setup
  before_script:

    - helm version

    # Install helm plugins
    - helm plugin list

    # Install Helmfile
    -  /home/linuxbrew/.linuxbrew/bin/helmfile --version
  script:
    - echo "Helm, Helmfile, and plugins installed successfully!"
  tags:
    - laptop

setup_secrets_operator:
  stage: setup
  before_script:
    # Update the package manager and install prerequisites
    - apt-get update && apt-get install -y curl apt-transport-https gnupg software-properties-common
  script:
    - |
      # Install SOPS
      sops -version

    - |
      # Install Age
      /home/linuxbrew/.linuxbrew/bin/age --version

    # Configure
    - cat $SOPS_FILE > .sops.yaml
  tags:
    - laptop

create-namespaces:
  stage: deploy
  script:
    - export KUBECONFIG=$DEV_KUBE_CONFIG
    - kubectl config get-contexts
    - echo "Checking and creating namespaces if they do not exist..."
    - |
      for NAMESPACE in dev stage; do
        if kubectl get namespace "$NAMESPACE" > /dev/null 2>&1; then
          echo "Namespace '$NAMESPACE' already exists."
        else
          echo "Creating namespace '$NAMESPACE'..."
          kubectl create namespace "$NAMESPACE"
        fi
      done
  needs:
  - setup_secrets_operator
  - setup_helm
  tags:
    - laptop

deploy-workload-helm-dev:
  stage: deploy
  script:
    - export KUBECONFIG=$DEV_KUBE_CONFIG
    - export SOPS_AGE_KEY_FILE=$SOPS_AGE_KEY_FILE
    - export SOPS_AGE_KEY=$SOPS_AGE_KEY
    - export HELM_SECRETS_AGE_KEY_FILE=$SOPS_AGE_KEY_FILE
    - /home/linuxbrew/.linuxbrew/bin/helmfile -e dev apply
  needs:
    - create-namespaces
  tags:
    - laptop


deploy-workload-helm-stage:
  stage: deploy
  script:
    - export KUBECONFIG=$DEV_KUBE_CONFIG
    - export SOPS_AGE_KEY_FILE=$SOPS_AGE_KEY_FILE
    - export SOPS_AGE_KEY=$SOPS_AGE_KEY
    - export HELM_SECRETS_AGE_KEY_FILE=$SOPS_AGE_KEY_FILE
    - /home/linuxbrew/.linuxbrew/bin/helmfile -e stage apply
  needs:
  - deploy-workload-helm-dev
  tags:
    - laptop
