workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == 'push' && $CI_OPEN_MERGE_REQUESTS && $CI_MERGE_REQUEST_TARGET_BRANCH_PROTECTED == 'true'
      when: never
    - when: always
                #when: always: This rule is a catch-all. 
                #It means that if none of the previous rules apply, the pipeline will always run.

before_script:
  - export PATH=$PATH:/home/linuxbrew/.linuxbrew/bin/

default:
  tags:
    - docker

stages:
  - setup
  - deploy

pre_kubeconfig:
  stage: .pre
  script:
    - echo "Setting up KUBECONFIG"
    - export KUBECONFIG=$DEV_KUBE_CONFIG  # Export KUBECONFIG variable for all stages
    - cat $DEV_KUBE_CONFIG > $CI_PROJECT_DIR/kubeconfig
  tags:
    - laptop
  artifacts:
    paths:
      - $CI_PROJECT_DIR/kubeconfig 
    expire_in: 1h  # Set artifact expiration
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

say_hello:
  stage: setup
  script:
    - echo "Say HELLLO!!"
  tags:
    - laptop

setup_helm:
  stage: setup
  before_script:

    - export PATH=$PATH:/usr/local/bin/
    - helm version

    # Install helm plugins
    - helm plugin list

    # Install Helmfile
    - helmfile --version
  allow_failure: true
  script:
    - echo "Helm, Helmfile, and plugins installed successfully!"
  tags:
    - laptop



